[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
caliber_payment = "FDeKt6Zc5KwmKHzEej3Cd7bhqxbw4pQoDikbY5roffye"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./provider_wallet.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/user-with-order.ts"

[[test.validator.account]]
address = "7UVimffxr9ow1uXYxsr4LHAcV58mLzhmwaeKvJ1pjLiE"
filename = "tests/sol_pyth_value_200.json"

[[test.validator.account]]
address = "Hhipna3EoWR7u8pDruUg8RxhP5F6XLh6SEHMVDmZhWi8"
filename = "tests/raydium_pyth_value_5.json"

