[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
caliber_payment = "FDeKt6Zc5KwmKHzEej3Cd7bhqxbw4pQoDikbY5roffye"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hoangphuc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.validator.account]]
address = "7UVimffxr9ow1uXYxsr4LHAcV58mLzhmwaeKvJ1pjLiE"
filename = "tests/sol_pyth.json"

